sourceName: SAP Springfield S/4HANA Activities
sourceId: sap_springfield_s4hana_activities
schemaSpace: sp_enterprise_process_industry
maintenanceOrderTransformationExternalId: sap_maintenance_orders_springfield_s4hana
operationTransformationExternalId: sap_operations_springfield_s4hana
operationToMaintenanceOrderTransformationExternalId: sap_operation_to_maintenance_order_springfield_s4hana
dataset: ingestion
organization: ORG
datamodelVersion: v1.0
instanceSpace: springfield_instances
rawSourceDatabase: ingestion

workflow: sap_s4hana_population_events
groupSourceId: <GROUP_SOURCE_ID>
workflowClientId: ${SAP_SPRINGFIELD_S4HANA_CLIENT_ID}
workflowClientSecret: ${SAP_SPRINGFIELD_S4HANA_CLIENT_SECRET}
