externalId: 'ep_ctx_entity_matching_metadata_update'
config:
  parameters:
    debug: False
    debugTimeseries: 'VAL_23-KA-9101-M01_E_stop_active:VALUE'
    runAll: True
    rawDb: 'ds_timeseries_{{location_name}}_{{source_name}}'
    rawTableState: 'ts_state_store'
  data:
    job:
      timeseriesView:
        schemaSpace: {{ schemaSpace }}
        instanceSpace: {{ timeseriesInstanceSpace }}
        externalId: {{organization}}TimeSeries
        version: {{ viewVersion }}
      assetView:
        schemaSpace: {{ schemaSpace }}
        instanceSpace: {{ assetInstanceSpace }}
        externalId: {{organization}}Asset
        version: {{ viewVersion }}