externalId: 'ep_ctx_timeseries_{{location_name}}_{{source_name}}_entity_matching'
config:
  parameters:
    debug: False
    runAll: True
    removeOldAssetLinks: True
    rawDb: '{{ dbName }}'
    rawTableState: 'contextualization_state_store'
    rawTaleCtxGood: 'contextualization_good'
    rawTaleCtxBad: 'contextualization_bad'
    rawTaleCtxManual: 'contextualization_manual_input'
    rawTaleCtxRule: 'contextualization_rule_input'
    autoApprovalThreshold: 0.85
  data:
    assetView:
      schemaSpace: {{ schemaSpace }}
      instanceSpace: {{ assetInstanceSpace }}
      externalId: {{organization}}Asset
      version: {{ viewVersion }}
      searchProperty: {{ AssetSearchProperty }}
      filterProperty: tags
      filterValues: {{ AssetFilterValues }}
    entityView:
      schemaSpace: {{ schemaSpace }}
      instanceSpace: {{ timeseriesInstanceSpace }}
      externalId: {{organization}}TimeSeries
      version: {{ viewVersion }}
      searchProperty: {{ EntitySearchProperty }}
      filterProperty: tags
      filterValues: {{ EntityFilterValues }}
