[library]
title = "official Cognite Deployment Packages"
description = """
The open-source Github repository ("Repository") is provided "as is", without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose, and non-infringement. Usage of the Repository is voluntary and in no event shall Cognite be liable for any claim, damages, or other liability, whether in an action of contract, tort, or otherwise, arising from, out of, or in connection with the use of the Repository.
"""


[packages.contextualization]
id = "dp:contextualization"
title = "Contextualization"
description = "Module templates for data contextualization"
modules = [
    "accelerators/contextualization/cdf_p_and_id_annotation",
    "accelerators/contextualization/cdf_file_annotation",
    "accelerators/contextualization/cdf_entity_matching",
]

[packages.models]
id = "dp:models"
title = "Data models"
description = "Data models that extend the core data model"
modules = [
    "models/rmdm_v1",
    "models/isa_manufacturing_extension",
]

[packages.atlas_ai]
id = "dp:atlas_ai"
title = "Atlas AI Deployment Pack"
description = "Deploy all Atlas AI modules in one package."
canCherryPick = true  # allows users to select individual modules
modules = [
    "atlas_ai/ootb_agents",
    "atlas_ai/rca_with_rmdm"
]

[packages.dashboards]
id = "dp:dashboards"
title = "Dashboards"
description = "Streamlit dashboards and visualization modules"
canCherryPick = true
modules = [
    "dashboards/context_quality"
]

