organization: ORG
function_version: v1.0.0
# Update your location
location_name: Springfield 
# specify the name of the source making it possible to identify where the data originates 
# from, ex: 'workmate', 'sap', 'oracle',..
# Update SOURCE to your source
source_name: springfield
dbName: db_entity_matching
contextualizationId: entity_matcher
contextualizationName: Entity Matcher
schemaSpace: sp_enterprise_process_industry
viewVersion: v1.0
assetInstanceSpace: springfield_instances
timeseriesInstanceSpace: springfield_instances
          
workflow: EntityMatching
### UPDATE THE FOLLOWING VALUES FOR YOUR IDP CONFIGURATION ###
workflowClientId: ${IDP_CLIENT_ID}
workflowClientSecret: ${IDP_CLIENT_SECRET}
# Update GROUP_SOURCE_ID to your group source ID
entity_matching_processing_group_source_id: <GROUP_SOURCE_ID>
