oidDatasetExternalId: ds_oid_sync
instanceSpace: springfield_instances
# Update GROUP_SOURCE_ID to your group source ID
groupSourceId: <GROUP_SOURCE_ID>
functionClientId: ${IDP_CLIENT_ID}
functionClientSecret: ${IDP_CLIENT_SECRET}
extractionPipelineExternalId: ep_oid_sync
functionExternalId: fn_oid_sync
functionSpace: springfield_functions
scheduleExternalId: schedule_oid_sync
scheduleCronExpression: "0 0 29 2 *"
openIdClientSecret: ${OPEN_ID_CLIENT_SECRET}
schemaSpace: sp_enterprise_process_industry
datamodelVersion: v1
reservedWordPrefix: Enterprise_
