sourceName: Springfield Sharepoint
sourceId: springfield_sharepoint
schemaSpace: sp_enterprise_process_industry
fileTransformationExternalId: files_metadata_springfield
dataset: ingestion
organization: ORG
datamodelVersion: v1.0
instanceSpace: springfield_instances
rawSourceDatabase: ingestion

groupSourceId: <GROUP_SOURCE_ID>
workflow: files_metadata_population
workflowClientId: ${SHAREPOINT_SERVICE_PRINCIPAL_CLIENT_ID}
workflowClientSecret: ${SHAREPOINT_SERVICE_PRINCIPAL_CLIENT_SECRET}
