sourceName: Springfield AVEVA PI
sourceId: springfield_aveva_pi
schemaSpace: sp_enterprise_process_industry
timeseriesTransformationExternalId: pi_timeseries_springfield_aveva_pi
dataset: ingestion
organization: ORG
datamodelVersion: v1.0
instanceSpace: springfield_instances
rawSourceDatabase: ingestion

