sourceName: Springfield AVEVA PI
sourceId: springfield_aveva_pi
schemaSpace: sp_enterprise_process_industry
timeseriesTransformationExternalId: pi_timeseries_springfield_aveva_pi
dataset: ingestion
datamodelExternalId: ORGProcessIndustries
datamodelVersion: v1
instanceSpace: springfield_instances
rawSourceDatabase: ingestion
reservedWordPrefix: Enterprise_
groupSourceId: <GROUP_SOURCE_ID>
workflow: aveva_pi_population
# TODO: Update to use the actual client ID and secret 'workflowClientId: ${AVEVA_PI_SPRINGFIELD_CLIENT_ID} & workflowClientSecret: ${AVEVA_PI_SPRINGFIELD_CLIENT_SECRET}'
workflowClientId: ${IDP_CLIENT_ID}
workflowClientSecret: ${IDP_CLIENT_SECRET}
