location: springfield
locationName: Springfield
organization: ORG
datamodelExternalId: ORGProcessIndustries
schemaSpace: sp_enterprise_process_industry
datamodelVersion: v1
instanceSpace: springfield_instances